app/originblog/blueprints/admin/views.py
from flask import Blueprint, render_template

from originblog.blueprints.admin.api import AdminIndex, Posts, PostItem, MetaPosts, MetaPostItem, Comments, \
    CommentItem, Users, MetaUserItem, Widgets, WidgetItem, PostStatistics, PostStatisticItem
from originblog.decorator import admin_required, permission_required
from originblog.forms.admin import PostForm, WidgetForm, MetaPostForm
from originblog.forms.auth import RegisterForm

admin_bp = Blueprint('admin', __name__)

# 注册路由
admin_bp.add_url_rule('/', view_func=AdminIndex.as_view('index'), methods=['GET'])

admin_bp.add_url_rule('/posts', view_func=Posts.as_view('posts'), methods=['GET', 'POST'])
admin_bp.add_url_rule('/posts/<slug>', view_func=PostItem.as_view('post'), methods=['GET', 'POST', 'PATCH', 'DELETE'])

admin_bp.add_url_rule('/pages', view_func=Posts.as_view('pages'), methods=['GET', 'POST'],
                      defaults={'post_type': 'page'})
admin_bp.add_url_rule('/pages/<slug>', view_func=PostItem.as_view('page'), methods=['GET', 'POST', 'PATCH', 'DELETE'])

admin_bp.add_url_rule('/meta/posts', view_func=MetaPosts.as_view('meta_posts'), methods=['GET', 'POST'])
admin_bp.add_url_rule('/meta/posts/<slug>', view_func=MetaPostItem.as_view('meta_post'), methods=['GET', 'POST'])

admin_bp.add_url_rule('/posts/comments', view_func=Comments.as_view('comments'), methods=['GET', 'DELETE'])
admin_bp.add_url_rule('/posts/comments/<pk>', view_func=CommentItem.as_view('comment'), methods=['PATCH', 'DELETE'])

admin_bp.add_url_rule('/users', view_func=Users.as_view('users'), methods=['GET', 'POST'])
admin_bp.add_url_rule('/meta/users/<pk>', view_func=MetaUserItem.as_view('meta_user'),
                      methods=['GET', 'POST', 'DELETE'])

admin_bp.add_url_rule('/widgets', view_func=Widgets.as_view('widgets'), methods=['GET', 'POST'])
admin_bp.add_url_rule('/widgets/<pk>', view_func=WidgetItem.as_view('widget'), methods=['GET', 'POST', 'DELETE'])

admin_bp.add_url_rule('/posts/statistics', view_func=PostStatistics.as_view('statistics'), methods=['GET'])
admin_bp.add_url_rule('/posts/statistics/<slug>', view_func=PostStatisticItem.as_view('statistic'), methods=['GET'])


@admin_bp.route('/posts/new_post')
@permission_required('POST')
def new_post():
    form = PostForm()
    form.type.data = 'post'
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/posts/add_user')
@permission_required('MODERATE')
def add_user():
    form = RegisterForm()
    return render_template('admin/new_user.html', form=form)


@admin_bp.route('/pages/new_page')
@admin_required
def new_page():
    form = PostForm()
    form.type.data = 'page'
    return render_template('admin/new_page.html', form=form)


@admin_bp.route('/widgets/new_widget')
@admin_required
def new_widget():
    form = WidgetForm()
    return render_template('admin/new_widget.html', form=form)


@admin_bp.route('/meta/posts/new_article')
@admin_required
def new_article():
    form = MetaPostForm()
    return render_template('admin/new_article.html', form=form)

app/originblog/blueprints/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, current_user, login_required, logout_user, login_fresh, confirm_login

from originblog.emails import send_confirm_email, send_reset_password_email
from originblog.forms.auth import LoginForm, RegisterForm, ForgetPasswordForm, ResetPasswordForm
from originblog.models import User, Role
from originblog.settings import Operations
from originblog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """处理用户登录"""
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        user = User.objects.filter(username=username).first()
        if user:
            if username == user.username and user.validate_password(password):
                login_user(user, remember)
                flash('Welcome back', 'info')
                return redirect_back()
            flash('Invalid username or password.', 'warning')
        else:
            flash('Invalid username or password.', 'warning')
    return render_template('auth/signin.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    """处理用户注销"""
    logout_user()
    flash('Logout success.', 'info')
    return redirect_back()


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    """处理用户注册"""
    if current_user.is_authenticated:
        redirect(url_for('blog.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        name = form.name.data
        username = form.username.data
        email = form.email.data.lower()
        password = form.password.data
        user = User(
            name=name,
            username=username,
            email=email
        )
        user.set_password(password)
        # 如果是第一次注册，初始化数据库
        if not Role.objects.first():
            Role.init()
        user.save()

        token = user.generate_token(Operations.CONFIRM)
        send_confirm_email(user=user, token=token)
        flash('Confirm email sent, check your inbox.', 'info')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)


@auth_bp.route('/confirm/<token>')
@login_required
def confirm(token):
    """通过令牌确认账户"""
    if current_user.email_confirmed:
        return redirect(url_for('blog.index'))

    if current_user.validate_token(token, Operations.CONFIRM):
        flash('Account confirmed.', 'info')
        return redirect(url_for('blog.index'))
    else:
        flash('Invalid or expired token.', 'danger')
        return redirect(url_for('auth.resend_confirm_email'))


@auth_bp.route('/resend-confirm-email')
@login_required
def resend_confirm_email():
    """重新生成令牌并发送邮件"""
    if current_user.confirmed:
        return redirect(url_for('blog.index'))

    token = current_user.generate_token(Operations.CONFIRM)
    send_confirm_email(user=current_user, token=token)
    flash('New email sent, check your inbox.', 'info')
    return redirect(url_for('blog.index'))


@auth_bp.route('/forget-password', methods=['GET', 'POST'])
def forget_password():
    """忘记密码时发送令牌重置密码"""
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    form = ForgetPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.objects.filter(email=email).first()

        if user:
            token = user.generate_token(Operations.RESET_PASSWORD)
            send_reset_password_email(user=user, token=token)
            flash('Password reset email sent, check your inbox.', 'info')
            return redirect(url_for('auth.login'))
        flash('Invalid email.', 'warning')
        return redirect(url_for('auth.forget_password'))
    return render_template('auth/forget_password.html', form=form)


@auth_bp.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """填写新密码，验证令牌并修改密码"""
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data
        user = User.objects.filter(email=email).first()
        if user is None:
            return redirect(url_for('blog.index'))
        if user.validate_token(token, Operations.RESET_PASSWORD, password):  # 在验证令牌方法中修改密码
            flash('Password updated.', 'success')
            return redirect(url_for('auth.login'))
        else:
            flash('Invalid or expired token.', 'danger')
            return redirect(url_for('auth.forget_password'))
    return render_template('auth/reset_password.html')


@auth_bp.route('re-authenticate', methods=['GET', 'POST'])
@login_required
def re_authenticate():
    """处理非新鲜登录的重认证"""
    if login_fresh():
        return redirect(url_for('blog.index'))

    form = LoginForm()
    if form.validate_on_submit() and current_user.validate_password(form.password.data):
        confirm_login()
        return redirect_back()
    return render_template('auth/signin.html', form=form)

app/originblog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for, flash, make_response
from flask_login import current_user
from mongoengine.queryset.visitor import Q

from originblog.forms.blog import CommentForm, UserCommentForm
from originblog.models import Post, Comment, Widget
from originblog.signals import post_visited
from originblog.utils import redirect_back, reply_filter

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    """构建博客首页

    查询所有已发表的文章，根据分类、标签、关键字搜索等特定查询参数进行筛选分页
    """
    # 获取已发表并且权重值大于0的文章的QuerySet，按权重和发表时间排序
    pub_posts = Post.objects.filter(type='post').order_by('-weight', '-pub_time')
    posts = pub_posts.filter(Q(weight__gt=0) | Q(weight=None))

    # 根据查询参数获取特定分类的文章
    category = request.args.get('category')
    if category:
        posts = posts.filter(category=category)

    # 根据查询参数获取特定标签的文章
    tag = request.args.get('tag')
    if tag:
        posts = posts.filter(tags=tag)

    # 根据查询参数获取特定文本关键词的搜索结果
    keywords = request.args.get('keywords')
    if keywords:
        posts = posts.filter(Q(raw_content__icontains=keywords) | Q(title__icontains=keywords))

    # 获取首页所有widgets
    widgets = Widget.objects

    # 从查询参数获取当前页数并对QuerySet分页
    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['APP_POST_PER_PAGE']
    pagination = posts.paginate(page, per_page=per_page)  # 分页对象

    return render_template('blog/index.html', pagination=pagination, widgets=widgets, cur_category=category,
                           cur_tag=tag, cur_keywords=keywords)


@blog_bp.route('/posts/<slug>', methods=['GET', 'POST'])
def show_post(slug, post_type='post'):
    """显示文章正文、评论列表与评论表单并处理表单提交。

    已登录用户不需要手动填写评论表单的个人信息,通过查询参数reply-to判断是否为评论回复，并进行相应处理
    :param slug: 文章的标题别名
    :param post_type: 显示的文章类型（用来区分专用页面）
    """
    post = Post.objects.get_or_404(slug=slug)

    # 若用户为认证用户，使用专门的评论表单
    if current_user.is_authenticated:
        form = UserCommentForm()
        form.author.data = current_user.name
        form.email.data = current_user.email
        form.homepage.data = current_user.homepage
    else:
        form = CommentForm()

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        homepage = form.homepage.data
        md_content = form.content.data
        comment = Comment(author=author, email=email, homepage=homepage, md_content=md_content, post_slug=post.slug,
                          post_title=post.title)
        reply_to = request.args.get('replyto')
        if reply_to:
            comment.reply_to = Comment.objects.get_or_404(pk=reply_to)
        message = 'Thanks, your comment will be published after reviewed.'
        # 管理员和文章作者发布的评论不需要审核
        if current_user.is_authenticated and current_user.username == post.author.username:
            comment.from_post_author = True
            comment.status = 'approved'
            message = 'Comment published.'
        if current_user.is_admin:
            comment.from_admin = True
            comment.status = 'approved'
            message = 'Comment published.'

        comment.save()
        flash(message, 'info')
        # 根据文章类型使用不同的端点
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        return redirect(url_for(endpoints[post_type], slug=slug))

    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['APP_COMMENT_PER_PAGE']
    comment_pagination = Comment.objects.filter(post_slug=post.slug, status='approved').paginate(page, per_page)
    # 发送文章被浏览的信号
    post_visited.send(current_app._get_current_object(), post=post)
    # 根据文章类型使用不同的模板
    templates = {
        'post': 'blog/post.html',
        'page': 'blog/page.html'
    }

    return render_template(templates.get(post_type, 'blog/post.html'), post=post, comment_pagination=comment_pagination,
                           form=form, reply_filter=reply_filter)


# 为专用页面page注册路由
blog_bp.add_url_rule('/pages/<slug>/', 'show_page', show_post, defaults={'post_type': 'page'}, methods=['GET', 'POST'])


@blog_bp.route('/reply/comment/<pk>', defaults={'post_type': 'post'})
@blog_bp.route('/reply/<post_type>/comment/<pk>')
def reply_comment(pk, post_type):
    """实现评论的回复功能

    以该视图作为中转传递被回复的评论的id。
    在show_post视图中获取查询参数并进行相应处理。
    :param pk: 被回复的comment id
    :param post_type: 发表评论的文章类型
    """
    comment = Comment.objects.get_or_404(pk=pk)
    post = Post.objects.get_or_404(slug=comment.post_slug)
    if post.can_comment:
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        return redirect(
            url_for(endpoints[post_type], slug=post.slug, replyto=pk,
                    author=comment.author) + '#comments')
    else:
        flash('This post is comment disabled.', 'warning')
        return redirect_back()


@blog_bp.route('/archive')
def archive():
    """按时间归档文章"""
    posts = Post.objects.filter(type='post').order_by('-pub_time').only('title', 'slug', 'pub_time')
    # 按月份分组所有post
    data = {}
    years = reversed(list(set([post.pub_time.year for post in posts])))
    for year in years:
        months = reversed(list(set([post.pub_time.month for post in posts if post.pub_time.year == year])))
        for month in months:
            post_items = [post for post in posts if post.pub_time.month == month]
            data[(year, month)] = post_items
    return render_template('blog/archive.html', data=data)


@blog_bp.route('/sitemap.xml/')
def sitemap():
    """Generate sitemap.xml. Makes a list of urls and date modified."""
    pages = []

    posts = Post.objects
    for post in posts:
        post_type = post.type
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        pages.append((url_for(endpoints[post_type], slug=post.slug, _external=True),
                      post.update_time.date(), 'weekly', '0.8'))

    sitemap_xml = render_template('blog/sitemap.xml', pages=pages)
    response = make_response(sitemap_xml)
    response.headers['Content-Type'] = 'application/xml'

    return response

app/originblog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- SEO optimize -->
    {% if post %}
    <meta name="title" content="{{ post.title }}">
    <meta name="description" content="{{ post.abstract }}">
    <meta name="author" content="{{ post.author.name }}">
    <meta name="keywords" content="{{ post.tags|join(',') }}">
    {% else %}
    <meta name="title" content="{{ blog_meta.name }}">
    <meta name="description" content="{{ blog_meta.description }}">
    <meta name="author" content="{{ blog_meta.owner }}">
    <meta name="keywords" content="{{ blog_meta.keywords }}">
    {% endif %}

    <meta name="google-site-verification" content="{{ blog_meta.google_site_verification }}"/>
    <meta name="baidu-site-verification" content="{{ blog_meta.baidu_site_verification }}"/>
    <meta name="sogou_site_verification" content="{{ blog_meta.sogou_site_verification }}"/>
    <meta name="qihu-site-verification" content="{{ blog_meta.qihu_site_verification }}"/>

    <title>Origin Blog - {% block title %}{% endblock %}</title>

    <link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='img/favicon-96x96.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon-16x16.png') }}">

    <!-- Bootstrap core CSS -->
    <link crossorigin="anonymous" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" href="https://lib.baomitu.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.8.1/css/all.min.css" integrity="sha256-7rF6RaSKyh16288E3hVdzQtHyzatA2MQRGu0cf6pqqM=" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='css/clean-blog.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">

    {% block custom_head %}{% endblock %}

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('blog.index') }}">{{ blog_meta.name }}</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                    data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                    aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.archive') }}">Archive</a>
                    </li>
                    {% if blog_meta.index_nav1 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.show_page', slug=blog_meta.index_nav1.lower()) }}">{{ blog_meta.index_nav1 }}</a>
                    </li>
                    {% endif %}
                    {% if blog_meta.index_nav2 %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.show_page', slug=blog_meta.index_nav2.lower()) }}">{{ blog_meta.index_nav2 }}</a>
                    </li>
                    {% endif %}
                    {% if not current_user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('auth.login', next=request.full_path) }}">Sign in</a>
                        </li>
                    {% else %}
                        <li class="dropdown nav-item">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-expanded="false">
                                User
                                <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" role="menu">
                                <h6 class="dropdown-header">Logged in as {{ current_user.username }}</h6>
                                <a class="dropdown-item" href="{{ url_for('user.index', username=current_user.username) }}">
                                    <span class="fas fa-fw fa-user"></span> Profile
                                </a>
                                <a class="dropdown-item" href="{{ url_for('user.edit_profile') }}">
                                    <span class="fas fa-fw fa-cog"></span> Settings
                                </a>
                                {% if current_user.can('POST') %}
                                    <a class="dropdown-item" href="{{ url_for('admin.index') }}">
                                        <span class="fas fa-fw fa-tachometer-alt"></span> Dashboard
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">
                                        <span class="fas fa-fw fa-pen"></span> New Post
                                    </a>
                                {% endif %}
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ url_for('auth.logout') }}">
                                    <span class="fas fa-fw fa-sign-out-alt"></span> Logout
                                </a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    {% block header %}
    <header class="masthead" style="background-image: url({{ blog_meta.bg_home }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <span class="subheading">{{ blog_meta.subtitle }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock %}

    <!-- Main Content -->
    <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
        {% endfor %}

        {% block main %}
        {% endblock %}
    </div>


    <!-- Footer -->
    {% block footer %}
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="mailto:ampedee@gmail.com">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-google fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/waynerv">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://weibo.com/u/2198233840/home?wvr=5&lf=reg">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-weibo fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Origin Blog 2019</p>
                </div>
            </div>
        </div>
    </footer>
    {% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script crossorigin="anonymous" integrity="sha384-JUMjoW8OzDJw4oFpWIB2Bu/c6768ObEthBMVSiIx4ruBIEdyNSUQAjJNFqT5pnJ6" src="https://lib.baomitu.com/jquery/3.4.0/jquery.min.js"></script>
    <script crossorigin="anonymous" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" src="https://lib.baomitu.com/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    {{ moment.include_moment(local_js="https://lib.baomitu.com/moment.js/2.24.0/moment-with-locales.min.js") }}
    <script src="{{ url_for('static', filename='js/clean-blog.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

    {% block scripts %}{% endblock %}
</body>

</html>

app/originblog/templates/macros.html
{% macro nav_link(endpoint, text) %}
    <li class="nav-item {% if request.endpoint and request.endpoint == endpoint %}active{% endif %}">
        <a class="nav-link" href="{{ url_for(endpoint, **kwargs) }}">{{ text }}</a>
    </li>
{% endmacro %}

{# Macro for creating pagination links #}
{% macro render_pagination(pagination, endpoint) %}
    <div class=pagination>
        {% for page in pagination.iter_pages() %}
            {% if page %}
                {% if page != pagination.page %}
                    <a href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a>
                {% else %}
                    <strong>{{ page }}</strong>
                {% endif %}
            {% else %}
                <span class=ellipsis>…</span>
            {% endif %}
        {% endfor %}
    </div>
{% endmacro %}

{% macro render_entire_pagination(pagination, endpoint) %}
  <nav>
    <ul class="pagination">
      {% if not pagination.has_prev %}
        <li class="disabled">
            <span aria-hidden="true">&laquo;</span>
        </li>
      {% else %}
        <li>
        <a href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
      {% endif %}

      {%- for page in pagination.iter_pages() %}
        {% if page %}
          {% if page != pagination.page %}
            <li><a href="{{ url_for(endpoint, page=page, **kwargs) }}">{{ page }}</a></li>
          {% else %}
            <li class="disabled"><a href="{{ url_for(endpoint, page=page, **kwargs) }}"><strong>{{ page }}</strong></a></li>
          {% endif %}
        {% else %}
          <!-- <span class=ellipsis>…</span> -->
          <li><a href="#">...</a></li>
        {% endif %}
      {%- endfor %}

      {% if not pagination.has_next %}
        <li class="disabled">
          <span aria-hidden="true">&raquo;</span>
        </li>
      {% else %}
        <li>
          <a href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endmacro %}

{% macro render_short_pagination(pagination, endpoint) %}
<nav>
    <ul class="pagination">
        {% if pagination.has_next %}
        <li class="next">
            <a href="{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}">Next</a>
        </li>
        {% endif %}
        {% if pagination.has_prev %}
        <li class="next">
            <a href="{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}">Previous</a>
        </li>
        {% endif %}
    </ul>
</nav>
{% endmacro %}