app/originblog/forms/blog.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, \
    HiddenField
from wtforms.validators import DataRequired, Length, Email, URL, Optional


class CommentForm(FlaskForm):
    """定义评论表单"""
    author = StringField('* Name', validators=[DataRequired(), Length(1, 30)])
    email = StringField('* Email', validators=[DataRequired(), Email(), Length(1, 254)])
    homepage = StringField('Homepage', validators=[Optional(), URL(), Length(0, 255)])
    content = TextAreaField('* Comment <span class="badge badge-info">markdown</span>',
                            validators=[DataRequired()])
    submit = SubmitField('Submit')


class UserCommentForm(FlaskForm):
    """定义已登录用户的评论表单"""
    author = HiddenField('* Name', validators=[DataRequired(), Length(1, 30)])
    email = HiddenField('* Email', validators=[DataRequired(), Email(), Length(1, 254)])
    homepage = HiddenField('Homepage', validators=[Optional(), URL(), Length(0, 255)])
    content = TextAreaField('* Comment <small><span class="badge badge-info">markdown</span></small>',
                            validators=[DataRequired()])
    submit = SubmitField('Submit')

app/originblog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, redirect, url_for, flash, make_response
from flask_login import current_user
from mongoengine.queryset.visitor import Q

from originblog.forms.blog import CommentForm, UserCommentForm
from originblog.models import Post, Comment, Widget
from originblog.signals import post_visited
from originblog.utils import redirect_back, reply_filter

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/')
def index():
    """构建博客首页

    查询所有已发表的文章，根据分类、标签、关键字搜索等特定查询参数进行筛选分页
    """
    # 获取已发表并且权重值大于0的文章的QuerySet，按权重和发表时间排序
    pub_posts = Post.objects.filter(type='post').order_by('-weight', '-pub_time')
    posts = pub_posts.filter(Q(weight__gt=0) | Q(weight=None))

    # 根据查询参数获取特定分类的文章
    category = request.args.get('category')
    if category:
        posts = posts.filter(category=category)

    # 根据查询参数获取特定标签的文章
    tag = request.args.get('tag')
    if tag:
        posts = posts.filter(tags=tag)

    # 根据查询参数获取特定文本关键词的搜索结果
    keywords = request.args.get('keywords')
    if keywords:
        posts = posts.filter(Q(raw_content__icontains=keywords) | Q(title__icontains=keywords))

    # 获取首页所有widgets
    widgets = Widget.objects

    # 从查询参数获取当前页数并对QuerySet分页
    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['APP_POST_PER_PAGE']
    pagination = posts.paginate(page, per_page=per_page)  # 分页对象

    return render_template('blog/index.html', pagination=pagination, widgets=widgets, cur_category=category,
                           cur_tag=tag, cur_keywords=keywords)


@blog_bp.route('/posts/<slug>', methods=['GET', 'POST'])
def show_post(slug, post_type='post'):
    """显示文章正文、评论列表与评论表单并处理表单提交。

    已登录用户不需要手动填写评论表单的个人信息,通过查询参数reply-to判断是否为评论回复，并进行相应处理
    :param slug: 文章的标题别名
    :param post_type: 显示的文章类型（用来区分专用页面）
    """
    post = Post.objects.get_or_404(slug=slug)

    # 若用户为认证用户，使用专门的评论表单
    if current_user.is_authenticated:
        form = UserCommentForm()
        form.author.data = current_user.name
        form.email.data = current_user.email
        form.homepage.data = current_user.homepage
    else:
        form = CommentForm()

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        homepage = form.homepage.data
        md_content = form.content.data
        comment = Comment(author=author, email=email, homepage=homepage, md_content=md_content, post_slug=post.slug,
                          post_title=post.title)
        reply_to = request.args.get('replyto')
        if reply_to:
            comment.reply_to = Comment.objects.get_or_404(pk=reply_to)
        message = 'Thanks, your comment will be published after reviewed.'
        # 管理员和文章作者发布的评论不需要审核
        if current_user.is_authenticated and current_user.username == post.author.username:
            comment.from_post_author = True
            comment.status = 'approved'
            message = 'Comment published.'
        if current_user.is_admin:
            comment.from_admin = True
            comment.status = 'approved'
            message = 'Comment published.'

        comment.save()
        flash(message, 'info')
        # 根据文章类型使用不同的端点
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        return redirect(url_for(endpoints[post_type], slug=slug))

    page = request.args.get('page', default=1, type=int)
    per_page = current_app.config['APP_COMMENT_PER_PAGE']
    comment_pagination = Comment.objects.filter(post_slug=post.slug, status='approved').paginate(page, per_page)
    # 发送文章被浏览的信号
    post_visited.send(current_app._get_current_object(), post=post)
    # 根据文章类型使用不同的模板
    templates = {
        'post': 'blog/post.html',
        'page': 'blog/page.html'
    }

    return render_template(templates.get(post_type, 'blog/post.html'), post=post, comment_pagination=comment_pagination,
                           form=form, reply_filter=reply_filter)


# 为专用页面page注册路由
blog_bp.add_url_rule('/pages/<slug>/', 'show_page', show_post, defaults={'post_type': 'page'}, methods=['GET', 'POST'])


@blog_bp.route('/reply/comment/<pk>', defaults={'post_type': 'post'})
@blog_bp.route('/reply/<post_type>/comment/<pk>')
def reply_comment(pk, post_type):
    """实现评论的回复功能

    以该视图作为中转传递被回复的评论的id。
    在show_post视图中获取查询参数并进行相应处理。
    :param pk: 被回复的comment id
    :param post_type: 发表评论的文章类型
    """
    comment = Comment.objects.get_or_404(pk=pk)
    post = Post.objects.get_or_404(slug=comment.post_slug)
    if post.can_comment:
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        return redirect(
            url_for(endpoints[post_type], slug=post.slug, replyto=pk,
                    author=comment.author) + '#comments')
    else:
        flash('This post is comment disabled.', 'warning')
        return redirect_back()


@blog_bp.route('/archive')
def archive():
    """按时间归档文章"""
    posts = Post.objects.filter(type='post').order_by('-pub_time').only('title', 'slug', 'pub_time')
    # 按月份分组所有post
    data = {}
    years = reversed(list(set([post.pub_time.year for post in posts])))
    for year in years:
        months = reversed(list(set([post.pub_time.month for post in posts if post.pub_time.year == year])))
        for month in months:
            post_items = [post for post in posts if post.pub_time.month == month]
            data[(year, month)] = post_items
    return render_template('blog/archive.html', data=data)


@blog_bp.route('/sitemap.xml/')
def sitemap():
    """Generate sitemap.xml. Makes a list of urls and date modified."""
    pages = []

    posts = Post.objects
    for post in posts:
        post_type = post.type
        endpoints = {
            'post': 'blog.show_post',
            'page': 'blog.show_page'
        }
        pages.append((url_for(endpoints[post_type], slug=post.slug, _external=True),
                      post.update_time.date(), 'weekly', '0.8'))

    sitemap_xml = render_template('blog/sitemap.xml', pages=pages)
    response = make_response(sitemap_xml)
    response.headers['Content-Type'] = 'application/xml'

    return response

app/originblog/templates/blog/_comment.html
<div class="comments" id="comments">
    <!-- comment header -->
    <div class="row">
        <div class="col">
            <hr>
            <h3>{{ comment_pagination.total }} Comments
                <small>
                    <a href="{{ url_for('blog.show_post', slug=post.slug, page=comment_pagination.pages or 1) }}#comments">
                        latest
                    </a>
                </small>
            {% if current_user.is_admin %}
                <button data-id="{{ post.id }}" data-href="{{ url_for('admin.post', slug=post.slug) }}"
                        class="btn btn-warning btn-sm d-inline float-right switch-comment" type="button">
                    {% if post.can_comment %}Disabled{% else %}Enable{% endif %} Comment
                </button>
            {% endif %}
            </h3>
        </div>
    </div>

    <!-- comment form -->
    <div class="row comment-form">
        <div class="col">
            {% if post.can_comment %}
                {% if request.args.get('replyto') %}
                <div class="alert alert-info" role="alert">
                    Reply to<strong>{{ request.args.get('author') }}</strong>:
                    <a class="float-right" href="{{ url_for('blog.show_post', slug=post.slug) }}#comments">Cancel</a>
                </div>
                {% endif %}
                <div id="comment-form">
                    <form class="form-group" action="{{ request.full_path }}" method="post">
                        {% if current_user.is_authenticated %}
                            {{ form.hidden_tag() }}
                        {% else %}
                            {{ form.csrf_token }}
                            {{ render_field(form.author) }}
                            {{ render_field(form.email) }}
                            {{ render_field(form.homepage) }}
                        {% endif %}
                        <div class="form-group">
                        {{ form.content.label(class_="form-control-label") }}
                        {{ form.content(class_="form-control", rows="5") }}
                        {% if form.content.errors %}
                            {% for message in form.content.errors %}
                            <small class="error">{{ message }}</small><br>
                            {% endfor %}
                        {% endif %}
                        </div>
                        {{ form.submit(class_="btn btn-primary") }}
                    </form>
                </div>
            {% else %}
                <div class="tip">
                    <h5>Comment disabled.</h5>
                </div>
            {% endif %}
        </div>
    </div>

    <!-- comment list -->
    <div class="row">
        <div class="col">
            {% if comment_pagination.items %}
            <ul class="list-unstyled">
                {% for comment in comment_pagination.items %}
                <div id="{{ comment.pk }}">
                <hr>
                <li class="media">
                    <img class="rounded img-fluid mr-3" src="{{ comment.get_avatar_url() }}">
                    <div class="media-body">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="my-1">
                                <a href="{% if comment.homepage %}{{ comment.homepage }}{% else %}#{% endif %}"
                                   target="_blank">
                                    {{ comment.author }}
                                </a>
                                {% if comment.from_post_author %}
                                    <span class="badge badge-primary">Author</span>
                                {% endif %}
                                {% if comment.from_admin %}
                                    <span class="badge badge-warning">Admin</span>
                                {% endif %}
                                {% if reply_filter(comment) %}
                                    <span class="badge badge-secondary">Reply</span>
                                {% endif %}
                            </h5>
                            <small data-toggle="tooltip" data-placement="top" data-delay="500"
                                   data-timestamp="{{ comment.pub_time.strftime('%Y-%m-%dT%H:%M:%SZ') }}">
                                {{ moment(comment.pub_time).fromNow(refresh=True) }}
                            </small>
                        </div>
                        {% if reply_filter(comment) %}
                            {# 处理回复评论被删除时直接引用所引发的异常 #}
                            {% if reply_filter(comment, False) %}
                            <div class="alert alert-info reply-body" role="alert">
                                <h6 class="alert-heading">{{ comment.reply_to.author }}:</h6>
                                {{ comment.reply_to.html_content|safe }}
                            </div>
                            {% else %}
                            <div class="alert alert-info reply-body text-muted" role="alert">
                                Original comment has been deleted.
                            </div>
                            {% endif %}
                        {% endif %}
                        <div class="comment-body">
                            <p>{{ comment.html_content|safe }}</p>
                        </div>
                        <div class="float-right">
                            <a class="btn btn-primary btn-sm"
                               href="{{ url_for('blog.reply_comment', pk=comment.pk) }}">Reply</a>
                            {% if current_user.is_authenticated %}
                            <a class="btn btn-info btn-sm" href="mailto:{{ comment.email }}">Email</a>
                            {% endif %}
                            {% if current_user.is_admin %}
                                <button data-id="{{ comment.pk }}" data-href="{{ url_for('admin.comment', pk=comment.pk) }}"
                                        data-toggle="modal" data-target="#confirm-delete"
                                        class="btn btn-danger btn-sm d-inline" type="button">Delete
                                </button>
                            {% endif %}
                        </div>
                    </div>
                </li>
                </div>
                {% if loop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </ul>
            <!-- comment pagination -->
            <br>
            <div class="pagination justify-content-center">
                {{ render_pagination(comment_pagination, fragment='#comments') }}
            </div>
            {% else %}
            <div class="tip"><h5>No comments.</h5></div>
            {% endif %}
        </div>
    </div>
</div>

app/originblog/templates/blog/_index_sidebar.html
<div class="col-lg-3 col-md-2">
    <h3>Search</h3>
    <hr>
    <form id="search-form" action="{{ url_for('blog.index') }}">
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <button type="submit" class="input-group-text fas fa-search"></button>
                </div>
                <input type="text" class="form-control" id="search" name="keywords" placeholder="search"
                value="{% if cur_keywords %}{{ cur_keywords }}{% endif %}">
            </div>
        </div>
    </form>
    <br>

    <h3>Tags</h3>
    <hr>
    {% if tags %}
    <div>
        {% for tag in tags %}
            {% if tag == cur_tag %}
                <a href="{{ url_for('blog.index', tag=tag) }}" class="badge badge-primary badge-pill">
                    {{ tag }}<i class="fas fa-times small rm-filter" aria-hidden="true"></i>
                </a>
            {% else %}
                <a href="{{ url_for('blog.index', tag=tag) }}" class="badge badge-secondary badge-pill">
                    {{ tag }}
                </a>
            {% endif %}
            &nbsp;
        {% endfor %}
    </div>
    {% endif %}
    <br>

    <h3>Category</h3>
    <hr>
    <div class="list-group">
        {% for category in categories %}
            {% if category and category.name %}
                {% if category.name == cur_category %}
                    <a href="{{ url_for('blog.index', category=category.name) }}"
                       class="list-group-item list-group-item-action d-flex align-items-center active category-list">{{ category.name }}
                        <span class="fas fa-times small rm-filter ml-2" aria-hidden="true"></span>
                        <span class="badge badge-light badge-pill ml-auto">&nbsp;{{ category.count }}&nbsp;</span></a>
                {% else %}
                    <a href="{{ url_for('blog.index', category=category.name) }}"
                       class="list-group-item list-group-item-action d-flex justify-content-between align-items-center category-list">{{ category.name }}
                        <span class="badge badge-secondary badge-pill">&nbsp;{{ category.count }}&nbsp;</span></a>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <br>

    {% for widget in widgets %}
    <h3>{{ widget.title | safe }}</h3>
    <hr>
    <div class="list-group">
        {{ widget.html_content | safe }}
    </div>
    {% endfor %}
</div>

app/originblog/templates/blog/_post_sidebar.html
<div class="col-lg-3 col-md-2">
    {% if current_user.is_admin %}
    <div class="sidebar-header">
        <a class="btn btn-info btn-sm" href="{{ url_for('admin.post', slug=post.slug) }}">Edit</a>
        <button data-id="{{ post.id }}" data-href="{{ url_for('admin.post', slug=post.slug) }}"
                data-toggle="modal" data-target="#delete-post"
                class="btn btn-danger btn-sm d-inline" type="button">Delete
        </button>
    </div>
    {% endif %}

    <h3>Search</h3>
    <hr>
    <form id="search-form" action="{{ url_for('blog.index') }}">
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <button type="submit" class="input-group-text fas fa-search"></button>
                </div>
                <input type="text" class="form-control" id="search" name="keywords" placeholder="search"
                value="{% if cur_keywords %}{{ cur_keywords }}{% endif %}">
            </div>
        </div>
    </form>
    <br>

    <h3>Tags</h3>
    <hr>
    {% if tags %}
    <div>
        {% for tag in tags %}
            {% if tag == cur_tag %}
                <a href="{{ url_for('blog.index', tag=tag) }}" class="badge badge-primary badge-pill">
                    {{ tag }}<i class="fas fa-times small rm-filter" aria-hidden="true"></i>
                </a>
            {% else %}
                <a href="{{ url_for('blog.index', tag=tag) }}" class="badge badge-secondary badge-pill">
                    {{ tag }}
                </a>
            {% endif %}
            &nbsp;
        {% endfor %}
    </div>
    {% endif %}
    <br>

    <h3>Category</h3>
    <hr>
    <div class="list-group">
        {% for category in categories %}
            {% if category and category.name %}
                {% if category.name == cur_category %}
                    <a href="{{ url_for('blog.index', category=category.name) }}"
                       class="list-group-item list-group-item-action d-flex align-items-center active category-list">{{ category.name }}
                        <span class="fas fa-times small rm-filter ml-2" aria-hidden="true"></span>
                        <span class="badge badge-light badge-pill ml-auto">&nbsp;{{ category.count }}&nbsp;</span></a>
                {% else %}
                    <a href="{{ url_for('blog.index', category=category.name) }}"
                       class="list-group-item list-group-item-action d-flex justify-content-between align-items-center category-list">{{ category.name }}
                        <span class="badge badge-secondary badge-pill">&nbsp;{{ category.count }}&nbsp;</span></a>
                {% endif %}
            {% endif %}
        {% endfor %}
    </div>
    <br>

    {% for widget in widgets %}
    <h3>{{ widget.title | safe }}</h3>
    <hr>
    <div class="list-group">
        {{ widget.html_content | safe }}
    </div>
    {% endfor %}

    <!-- Table of Content-->
    <div class="post-toc d-none d-lg-block">
        <h3>Table of Content</h3>
        <hr>
        <div class="toc-list">
            <ol id="toc" data-toc="#main-content" data-toc-headings="h2,h3,h4"></ol>
        </div>
    </div>
</div>

app/originblog/templates/blog/archive.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}Archive{% endblock %}

{% block header %}
    <header class="masthead" style="background-image: url({{ blog_meta.bg_about }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>Archive</h1>
                        <hr class="small">
                        <span class="subheading">{{ blog_meta.subtitle }} <a href="{{ url_for('blog.index') }}"><i class="fa fa-rss"></i></a></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto" id="post-list">
            {% for (date, posts) in data.items() %}
            <div class="row mb-3">
                <div class="col">
                    <h3>{{ date[0] }}年{{ date[1] }}月（{{ posts|length }}）</h3>
                    <ul class="list-group list-group-flush">
                    {% for post in posts %}
                        <li class="list-group-item list-group-item-action">
                            <a href="{{ url_for('blog.show_post', slug=post.slug) }}">{{ post.title }}</a>&nbsp;
                            <span class="text-muted">{{ moment(post.pub_time).format('YYYY-MM-DD') }}</span>
                        </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <hr>
{% endblock %}

{% block scripts %}
{{ moment.include_moment(local_js="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment-with-locales.min.js") }}
{% endblock %}

app/originblog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import render_entire_pagination %}

{% block title %}Home{% endblock %}

{% block header %}
    <header class="masthead" style="background-image: url({{ blog_meta.bg_home }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>{{ blog_meta.name }}</h1>
                        <span class="subheading">{{ blog_meta.subtitle }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <!-- Post List-->
            {% for post in pagination.items %}
                {% if post %}
                    <div class="post-preview">
                        <a href="{{ url_for('blog.show_post', slug=post.slug) }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                        </a>
                        <p class="post-subtitle">
                            {{ post.abstract|striptags|truncate }}
                        </p>
                        <p class="post-meta">Posted by
                            <a href="{{ url_for('user.index', username=post.author.username) }}">{{ post.author.name }}</a>
                            on {{ moment(post.pub_time).format('YYYY/MM/DD, h:mm a') }}</p>
                        <p class="post-meta">category: <a
                                href="{{ url_for('blog.index', category=post.category) }}">{{ post.category }}</a>
                        </p>
                        <p class="post-meta">Tags:
                            {% for tag in post.tags %}
                                <a href="{{ url_for('blog.index', tag=tag) }}">{{ tag }}</a>{% endfor %}
                        </p>
                    </div>
                    {% if not loop.last %}
                        <hr>
                    {% endif %}
                {% else %}
                    <P class="post-subtitle">
                        No articles found here
                    </P>
                {% endif %}
            {% endfor %}

            <!-- Pagination -->
            <div class="clearfix">
                {% if pagination.has_next %}
                <a class="btn btn-primary float-right ml-2" href="{{ url_for('blog.index', page=pagination.next_num) }}
                    {%- if cur_category %}&category={{ cur_category }}{% endif %}
                    {%- if cur_keywords %}&keywords={{ cur_keywords }}{% endif %}
                    {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Older Posts &rarr;
                </a>
                {% endif %}
                {% if pagination.has_prev %}
                <a class="btn btn-primary float-right" href="{{ url_for('blog.index', page=pagination.prev_num) }}
                    {%- if cur_category %}&category={{ cur_category }}{% endif %}
                    {%- if cur_keywords %}&keywords={{ cur_keywords }}{% endif %}
                    {%- if cur_tag %}&tag={{ cur_tag }}{% endif %}">Previous Posts
                </a>
                {% endif %}
            </div>
        </div>

        <!--include sidebar template -->
        {% include 'blog/_index_sidebar.html' %}

    </div>

    <hr>
{% endblock main %}

{% block scripts %}
    <script type="text/javascript">
        $('.rm-filter').on('click', function (event) {

            location.href = "/";
            return false;
        });
    </script>
{% endblock %}

app/originblog/templates/blog/page.html
{% extends 'base.html' %}

{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'bootstrap/form.html' import render_field %}

{% block custom_head %}
    <link crossorigin="anonymous" integrity="sha384-snvkDYLVttT3SBWz8WVvdGfmManlusUoAT3Agqco/8yBV7/tlflWJCUmP2O9f9wF" href="https://lib.baomitu.com/highlight.js/9.15.6/styles/github.min.css" rel="stylesheet">
{% endblock %}

{% block title %}{{ post.title }}{% endblock title %}

{% block header %}
    <header class="masthead" style="background-image: url({{ blog_meta.bg_about }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>{{ post.title }}</h1>
                        <hr class="small">
                        <span class="meta">Posted by
                            <a href="{{ url_for('user.index', username=post.author.username) }}">{{ post.author.name }}</a>
                            on {{ moment(post.pub_time).format('YYYY/MM/DD, h:mm a') }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block main %}

    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            <!-- main content -->
            <article id="main-content">
                {{ post.html_content|safe }}
            </article>

            <!-- comment form and list -->
            {% include 'blog/_comment.html' %}

        </div>

    </div>

    <!-- Delete Modal-->
    {% if current_user.is_admin %}
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmModalLabel">Delete Confirm</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Are you sure you want to delete this item?</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary btn-sm" type="button" data-dismiss="modal">Cancel</button>
                    <button data-id="" data-href="" type="button" data-dismiss="modal"
                            class="btn btn-danger btn-sm delete-item">Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Custom Toast-->
    <div id="toast"></div>

{% endblock main %}

{% block scripts %}
    <script crossorigin="anonymous" integrity="sha384-CWWTkjyKvLwc1j/u6LmdJiGCWFkQtH9MxBpmgzrFFwMhF5qM2u/FzXrhV3nUfs0l" src="https://lib.baomitu.com/highlight.js/9.15.6/highlight.min.js"></script>
    <script type="text/javascript">
        hljs.initHighlightingOnLoad();
        // 生成csrf令牌
        var csrf_token = "{{ csrf_token() }}";
        var default_error_message = 'Server error, please try again later';
    </script>
{% endblock %}